version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: obracheck_postgres
    environment:
      POSTGRES_DB: constructionsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "6969:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d constructionsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  obracheck-backend:
    build: .
    container_name: obracheck_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/constructionsdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      SERVER_PORT: 8080
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: obracheck_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@obracheck.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
