server:
  address: 0.0.0.0

spring:
  application:
    name: construction
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # límite por archivo (ajusta si quieres)
      max-request-size: 50MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6969/constructionsdb}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
