spring:
  application:
    name: construction

  datasource:
    url: jdbc:postgresql://localhost:6969/constructionsdb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

